### ISSUE TITLE
train.txt file not available

### ISSUE THREAD

**Issue by anindya2001** [ExplainableML/sketch-primitives#1]
Hi,

I tried to reproduce your paper by following the instructions on the readme file. However, while I tried to train the sketch classifier on the Quickdraw dataset, I found that the train.txt file is missing. Can you please share the file and/or update the repository with it?

Thanking you,
Anindya

**Comment by salaniz** [comment]
Hi Anindya,

I uploaded a new version of the dataset that now contains the previously missing txt files and fixed the download script in 2d594ed0f02bbb5c7d612f34e44686e180a1b99a.

Please try again and see if it now works. Let me know if there are any more issues.

**Comment by anindya2001** [comment]
It is working. Thanks!
