### ISSUE TITLE
Error: No module named 'utils.flags'

### ISSUE THREAD

**Issue by panda7777777** [ExplainableML/sketch-primitives#3]
Hi,

I hope this message finds you well. I am currently reproducing with your work and attempted to run the `save_processed_images.py` script using the following command:

```
python save_processed_images.py --log-name chairv2_processed --model-type none --dataset chairv2
```

However, I encountered an import error which states: `No module named 'utils.flags'`. I've checked for common issues such as the working directory and dependencies, but the issue persists. Could you please advise on how to resolve this error? Any guidance or suggestions regarding the required environment setup or dependencies would be greatly appreciated.

Thank you for your time and assistance. I look forward to exploring your work further.

![IMG_0555](https://github.com/ExplainableML/sketch-primitives/assets/97934971/4c77c122-5ad6-4044-af09-6e3c6c816489)

**Comment by panda7777777** [comment]
You made a mistake with the import statement, the 'from util.flags import parser' should be changed to 'from utils.arguments import parser'.

**Comment by salaniz** [comment]
Thank you for pointing this out. It should now be fixed.
